"""AI Contribution Report ("AI disclosure") for a paper — deterministic, no LLM call.

Data sources (persisted PostgreSQL tables, the authoritative record):

- ``ai_sessions`` rows written by :func:`src.services.usage_tracking.record_ai_usage` after every
  streamed AI interaction: task type, timestamp and LLM provider/model (``metadata``). Newer rows
  also carry the raw task name (``metadata.task`` — ``TaskType`` has no ``EDIT`` member, so edits
  used to be stored as ``CHAT``) and the revision they produced (``metadata.revision_id``).
  Empty placeholder rows created when a paper is initialised are ignored.
- ``suggestions`` rows: the diff-based revisions the author accepts or rejects in the editor.

The in-memory session store is a no-database dev fallback without auth or usage tracking, so the
report never reads it (the papers API already requires a database). ``audit_logs`` is not written
by any code path today, so ``suggestions.status`` is the source of truth for accept/reject.

Everything below the "DB loading" section is pure and unit-testable without a database.
"""

from __future__ import annotations

import uuid
from collections import Counter
from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass
from datetime import UTC, datetime, timedelta

from sqlalchemy import func
from sqlalchemy.orm import Session

from src.db.models import AiSession, Suggestion
from src.models.ai_disclosure_schemas import (
    AiDisclosureAttribution,
    AiDisclosureCounts,
    AiDisclosureLocalizedText,
    AiDisclosureModelRow,
    AiDisclosurePeriod,
    AiDisclosureReport,
    AiDisclosureTaskRow,
    AiDisclosureTotals,
)

# Canonical order used for the breakdown and for the task list in the statement.
TASK_ORDER: tuple[str, ...] = ("style", "edit", "structure", "template", "citation", "logic", "chat")

# Legacy rows (no ``metadata.task``) that may have produced a diff suggestion: style, and edit stored as CHAT.
_LEGACY_SUGGESTION_TASKS = frozenset({"style", "chat"})

# A suggestion is written during the request, the usage row right after the stream finishes.
INFERENCE_WINDOW = timedelta(minutes=10)

DATA_SOURCES: tuple[str, ...] = ("ai_sessions", "suggestions")

PROVIDER_LABELS: dict[str, str] = {
    "google": "Google Gemini",
    "openrouter": "OpenRouter",
    "zai": "Z.AI GLM",
    "openai": "OpenAI",
    "anthropic": "Anthropic Claude",
}

_TASK_PHRASES: dict[str, dict[str, str]] = {
    "en": {
        "style": "improve the language, grammar and style of selected passages",
        "edit": "draft and revise text at the author's request",
        "structure": "analyse the structure of the manuscript",
        "template": "generate a LaTeX manuscript template",
        "citation": "check and verify bibliographic references",
        "logic": "audit the logical consistency of the argumentation",
        "chat": "answer questions about the manuscript",
    },
    "vi": {
        "style": "cải thiện ngôn ngữ, ngữ pháp và văn phong của các đoạn được chọn",
        "edit": "soạn thảo và chỉnh sửa văn bản theo yêu cầu của tác giả",
        "structure": "phân tích cấu trúc bản thảo",
        "template": "tạo khung mẫu LaTeX cho bản thảo",
        "citation": "kiểm tra và xác minh tài liệu tham khảo",
        "logic": "rà soát tính nhất quán logic của lập luận",
        "chat": "trả lời các câu hỏi về bản thảo",
    },
}

_LATEX_HEADINGS = {
    "en": "Declaration of generative AI and AI-assisted technologies in the writing process",
    "vi": "Tuyên bố về việc sử dụng AI tạo sinh và công nghệ hỗ trợ bởi AI trong quá trình viết",
}

_LATEX_COMMENTS = {
    "en": "% AI disclosure generated by Arionear on {date}. Review and adapt before inserting.",
    "vi": "% Tuyên bố sử dụng AI do Arionear tạo ngày {date}. Hãy xem lại và điều chỉnh trước khi chèn.",
}

_LATEX_ESCAPES: dict[str, str] = {
    "\\": r"\textbackslash{}",
    "&": r"\&",
    "%": r"\%",
    "$": r"\$",
    "#": r"\#",
    "_": r"\_",
    "{": r"\{",
    "}": r"\}",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
    "<": r"\textless{}",
    ">": r"\textgreater{}",
    "|": r"\textbar{}",
}

_RESOLVED_STATUSES = frozenset({"accepted", "modified", "rejected"})


# ─── Input records ───────────────────────────────────────────────────────────


@dataclass(frozen=True)
class InteractionRecord:
    """One recorded AI interaction (an ``ai_sessions`` usage row)."""

    id: str
    task: str
    created_at: datetime
    provider: str | None = None
    model: str | None = None
    revision_id: str | None = None
    # True when the row predates ``metadata.task``: the task was derived from ``task_type``.
    legacy: bool = False


@dataclass(frozen=True)
class SuggestionRecord:
    """One diff-based AI suggestion (a ``suggestions`` row)."""

    id: str
    status: str
    created_at: datetime


def as_utc(value: datetime) -> datetime:
    """SQLite returns naive datetimes; PostgreSQL returns aware ones. Normalise to aware UTC."""
    if value.tzinfo is None:
        return value.replace(tzinfo=UTC)
    return value.astimezone(UTC)


def normalize_task(value: object) -> str:
    raw = str(getattr(value, "value", value) or "").strip().lower()
    return raw if raw in TASK_ORDER else "chat"


def normalize_status(value: object) -> str:
    raw = str(getattr(value, "value", value) or "").strip().lower()
    return raw if raw in _RESOLVED_STATUSES else "pending"


def _clean(value: object) -> str | None:
    text = str(value or "").strip()
    return text or None


def interaction_from_row(
    *,
    session_id: object,
    task_type: object,
    created_at: datetime,
    metadata: Mapping | None,
    tokens_used: int | None,
    input_chars: int | None,
    output_chars: int | None,
) -> InteractionRecord | None:
    """Convert an ``ai_sessions`` row; returns ``None`` for empty placeholder sessions."""
    if (tokens_used or 0) <= 0 and (input_chars or 0) <= 0 and (output_chars or 0) <= 0:
        return None
    md = metadata if isinstance(metadata, Mapping) else {}
    raw_task = str(md.get("task") or "").strip().lower()
    known_task = raw_task in TASK_ORDER
    revision_id = _clean(md.get("revision_id"))
    return InteractionRecord(
        id=str(session_id),
        task=raw_task if known_task else normalize_task(task_type),
        created_at=as_utc(created_at),
        provider=(_clean(md.get("llm_provider")) or "").lower() or None,
        model=_clean(md.get("llm_model")),
        revision_id=revision_id.lower() if revision_id else None,
        legacy=not raw_task,
    )


def suggestion_from_row(*, suggestion_id: object, status: object, created_at: datetime) -> SuggestionRecord:
    return SuggestionRecord(
        id=str(suggestion_id).lower(),
        status=normalize_status(status),
        created_at=as_utc(created_at),
    )


# ─── Aggregation ─────────────────────────────────────────────────────────────


@dataclass(frozen=True)
class SuggestionAttribution:
    task_by_suggestion: dict[str, str | None]
    task_by_interaction: dict[str, str]
    linked: int
    inferred: int
    unattributed: int


def attribute_suggestions(
    interactions: Sequence[InteractionRecord],
    suggestions: Sequence[SuggestionRecord],
    *,
    window: timedelta = INFERENCE_WINDOW,
) -> SuggestionAttribution:
    """Match each suggestion to the interaction (task) that produced it.

    1. ``linked``: the interaction recorded the suggestion id in ``metadata.revision_id``.
    2. ``inferred``: legacy rows only — the first unclaimed style/chat interaction recorded within
       ``window`` after the suggestion (usage is recorded right after the stream that produced it).
       A legacy ``CHAT`` row that produced a suggestion was an edit, so it is relabelled ``edit``.
    3. ``unattributed``: anything else (e.g. suggestions from the non-streaming endpoints).
    """
    by_revision = {i.revision_id: i for i in interactions if i.revision_id}
    task_by_interaction = {i.id: i.task for i in interactions}
    candidates = sorted(
        (i for i in interactions if i.legacy and i.task in _LEGACY_SUGGESTION_TASKS),
        key=lambda i: (i.created_at, i.id),
    )
    claimed: set[str] = set()
    task_by_suggestion: dict[str, str | None] = {}
    linked = inferred = unattributed = 0

    for suggestion in sorted(suggestions, key=lambda s: (s.created_at, s.id)):
        source = by_revision.get(suggestion.id)
        if source is not None:
            task_by_suggestion[suggestion.id] = source.task
            linked += 1
            continue
        match = next(
            (
                c
                for c in candidates
                if c.id not in claimed and suggestion.created_at <= c.created_at <= suggestion.created_at + window
            ),
            None,
        )
        if match is None:
            task_by_suggestion[suggestion.id] = None
            unattributed += 1
            continue
        claimed.add(match.id)
        task = "edit" if match.task == "chat" else match.task
        task_by_interaction[match.id] = task
        task_by_suggestion[suggestion.id] = task
        inferred += 1

    return SuggestionAttribution(
        task_by_suggestion=task_by_suggestion,
        task_by_interaction=task_by_interaction,
        linked=linked,
        inferred=inferred,
        unattributed=unattributed,
    )


def _count_statuses(statuses: Iterable[str]) -> AiDisclosureCounts:
    tally = Counter(statuses)
    return AiDisclosureCounts(
        proposed=sum(tally.values()),
        accepted=tally["accepted"],
        modified=tally["modified"],
        rejected=tally["rejected"],
        pending=tally["pending"],
    )


def provider_label(provider: str | None) -> str | None:
    if not provider:
        return None
    return PROVIDER_LABELS.get(provider, provider)


def aggregate_models(interactions: Sequence[InteractionRecord]) -> list[AiDisclosureModelRow]:
    tally = Counter((i.provider, i.model) for i in interactions if i.provider or i.model)
    rows = [
        AiDisclosureModelRow(
            provider=provider,
            provider_label=provider_label(provider),
            model=model,
            interactions=count,
        )
        for (provider, model), count in tally.items()
    ]
    return sorted(rows, key=lambda r: (-r.interactions, r.provider or "", r.model or ""))


def describe_model(row: AiDisclosureModelRow, lang: str = "en") -> str:
    if row.model and row.provider_label:
        via = "qua" if lang == "vi" else "via"
        return f"{row.model} {via} {row.provider_label}"
    return row.model or row.provider_label or ""


# ─── Text generation ─────────────────────────────────────────────────────────


def escape_latex(text: str) -> str:
    """Escape LaTeX special characters in plain text (single pass, so escapes are never doubled)."""
    return "".join(_LATEX_ESCAPES.get(ch, ch) for ch in text)


def join_list(items: Sequence[str], lang: str) -> str:
    """'a', 'a and b', 'a, b, and c' (EN) / 'a', 'a và b', 'a, b và c' (VI)."""
    items = [item for item in items if item]
    if not items:
        return ""
    if len(items) == 1:
        return items[0]
    if lang == "vi":
        return f"{', '.join(items[:-1])} và {items[-1]}"
    if len(items) == 2:
        return f"{items[0]} and {items[1]}"
    return f"{', '.join(items[:-1])}, and {items[-1]}"


def _no_usage_statement(lang: str) -> str:
    if lang == "vi":
        return (
            "Không ghi nhận việc sử dụng trợ lý viết AI của Arionear cho bản thảo này; "
            "báo cáo này không bao gồm các công cụ AI được sử dụng ngoài Arionear."
        )
    return (
        "No use of Arionear's AI writing assistant was recorded for this manuscript; "
        "this report does not cover AI tools used outside Arionear."
    )


def _usage_sentence(lang: str, tasks: Sequence[str], model_names: Sequence[str]) -> str:
    phrases = [_TASK_PHRASES[lang][task] for task in tasks]
    if lang == "vi":
        models = f" (mô hình: {join_list(model_names, 'vi')})" if model_names else ""
        purpose = join_list(phrases, "vi") or "đề xuất chỉnh sửa văn bản"
        return (
            "Trong quá trình chuẩn bị công trình này, (các) tác giả đã sử dụng Arionear, "
            f"một trợ lý viết dựa trên AI{models}, để {purpose}."
        )
    noun = "model" if len(model_names) == 1 else "models"
    models = f" ({noun}: {join_list(model_names, 'en')})" if model_names else ""
    purpose = join_list(phrases, "en") or "propose revisions to the text"
    return (
        f"During the preparation of this work the author(s) used Arionear, an AI writing assistant{models}, "
        f"to {purpose}."
    )


def _review_sentences(lang: str, totals: AiDisclosureCounts) -> list[str]:
    accepted_total = totals.accepted + totals.modified
    if lang == "vi":
        if totals.proposed == 0:
            return [
                "Không có đề xuất chỉnh sửa văn bản nào của AI được ghi nhận qua bước chấp nhận/từ chối "
                "dựa trên diff của Arionear."
            ]
        accepted = f"{accepted_total} được chấp nhận"
        if totals.modified:
            accepted += f" (trong đó {totals.modified} được tác giả sửa lại trước khi chấp nhận)"
        parts = [accepted, f"{totals.rejected} bị từ chối"]
        if totals.pending:
            parts.append(f"{totals.pending} chưa được quyết định")
        sentences = [
            f"Arionear đã đề xuất {totals.proposed} chỉnh sửa văn bản, mỗi chỉnh sửa được hiển thị dưới dạng diff "
            f"và cần (các) tác giả chấp nhận hoặc từ chối một cách tường minh: {join_list(parts, 'vi')}."
        ]
        if accepted_total == 0:
            sentences.append("Không có đề xuất chỉnh sửa nào của AI được đưa vào bản thảo.")
        return sentences

    if totals.proposed == 0:
        return ["No AI-proposed text revisions were recorded through Arionear's diff-based accept/reject step."]
    plural = "" if totals.proposed == 1 else "s"
    accepted = f"{accepted_total} accepted"
    if totals.modified:
        accepted += f" ({totals.modified} after modification by the author(s))"
    parts = [accepted, f"{totals.rejected} rejected"]
    if totals.pending:
        parts.append(f"{totals.pending} left undecided")
    sentences = [
        f"Arionear proposed {totals.proposed} text revision{plural}, each shown as a diff that required "
        f"explicit acceptance or rejection by the author(s): {join_list(parts, 'en')}."
    ]
    if accepted_total == 0:
        sentences.append("None of the AI-proposed revisions were accepted into the manuscript.")
    return sentences


def _responsibility_sentence(lang: str) -> str:
    if lang == "vi":
        return (
            "(Các) tác giả đã xem xét, chỉnh sửa nội dung khi cần thiết và chịu hoàn toàn trách nhiệm "
            "về nội dung của công bố."
        )
    return (
        "The author(s) reviewed and edited the content as needed and take(s) full responsibility "
        "for the content of the publication."
    )


def build_statement(
    lang: str,
    *,
    has_ai_usage: bool,
    tasks: Sequence[str],
    model_names: Sequence[str],
    totals: AiDisclosureCounts,
) -> str:
    if not has_ai_usage:
        return _no_usage_statement(lang)
    sentences = [
        _usage_sentence(lang, tasks, model_names),
        *_review_sentences(lang, totals),
        _responsibility_sentence(lang),
    ]
    return " ".join(sentences)


def build_latex_snippet(lang: str, statement: str, generated_at: datetime) -> str:
    comment = _LATEX_COMMENTS[lang].format(date=as_utc(generated_at).date().isoformat())
    heading = escape_latex(_LATEX_HEADINGS[lang])
    return f"{comment}\n\\section*{{{heading}}}\n{escape_latex(statement)}\n"


# ─── Report ──────────────────────────────────────────────────────────────────


def build_ai_disclosure_report(
    *,
    paper_id: str,
    paper_title: str,
    interactions: Sequence[InteractionRecord],
    suggestions: Sequence[SuggestionRecord],
    generated_at: datetime | None = None,
) -> AiDisclosureReport:
    generated = as_utc(generated_at or datetime.now(UTC))
    attribution = attribute_suggestions(interactions, suggestions)

    interaction_tasks = Counter(attribution.task_by_interaction[i.id] for i in interactions)
    statuses_by_task: dict[str | None, list[str]] = {}
    for suggestion in suggestions:
        task = attribution.task_by_suggestion.get(suggestion.id)
        statuses_by_task.setdefault(task, []).append(suggestion.status)

    by_task: list[AiDisclosureTaskRow] = []
    for task in TASK_ORDER:
        counts = _count_statuses(statuses_by_task.get(task, []))
        if interaction_tasks[task] == 0 and counts.proposed == 0:
            continue
        by_task.append(AiDisclosureTaskRow(task=task, interactions=interaction_tasks[task], **counts.model_dump()))

    suggestion_totals = _count_statuses(s.status for s in suggestions)
    totals = AiDisclosureTotals(interactions=len(interactions), **suggestion_totals.model_dump())
    models = aggregate_models(interactions)
    has_ai_usage = bool(interactions) or bool(suggestions)
    tasks = [row.task for row in by_task]

    timestamps = [i.created_at for i in interactions] + [s.created_at for s in suggestions]
    period = AiDisclosurePeriod(
        first_interaction_at=min(timestamps) if timestamps else None,
        last_interaction_at=max(timestamps) if timestamps else None,
    )

    statements = {
        lang: build_statement(
            lang,
            has_ai_usage=has_ai_usage,
            tasks=tasks,
            model_names=list(dict.fromkeys(name for name in (describe_model(m, lang) for m in models) if name)),
            totals=suggestion_totals,
        )
        for lang in ("en", "vi")
    }

    return AiDisclosureReport(
        paper_id=paper_id,
        paper_title=paper_title,
        generated_at=generated,
        has_ai_usage=has_ai_usage,
        period=period,
        totals=totals,
        by_task=by_task,
        unattributed=_count_statuses(statuses_by_task.get(None, [])),
        models=models,
        attribution=AiDisclosureAttribution(
            linked=attribution.linked,
            inferred=attribution.inferred,
            unattributed=attribution.unattributed,
        ),
        statement=AiDisclosureLocalizedText(**statements),
        latex=AiDisclosureLocalizedText(
            en=build_latex_snippet("en", statements["en"], generated),
            vi=build_latex_snippet("vi", statements["vi"], generated),
        ),
        data_sources=list(DATA_SOURCES),
    )


# ─── DB loading ──────────────────────────────────────────────────────────────


def collect_ai_disclosure_inputs(
    db: Session, paper_id: uuid.UUID
) -> tuple[list[InteractionRecord], list[SuggestionRecord]]:
    """Load the paper's AI interactions and suggestions without pulling prompt/output text."""
    session_rows = (
        db.query(
            AiSession.id,
            AiSession.task_type,
            AiSession.created_at,
            AiSession.metadata_,
            AiSession.tokens_used,
            func.coalesce(func.length(AiSession.user_input), 0),
            func.coalesce(func.length(AiSession.ai_output), 0),
        )
        .filter(AiSession.paper_id == paper_id)
        .all()
    )
    interactions = [
        record
        for record in (
            interaction_from_row(
                session_id=sid,
                task_type=task_type,
                created_at=created_at,
                metadata=metadata,
                tokens_used=tokens_used,
                input_chars=input_chars,
                output_chars=output_chars,
            )
            for sid, task_type, created_at, metadata, tokens_used, input_chars, output_chars in session_rows
        )
        if record is not None
    ]

    suggestion_rows = (
        db.query(Suggestion.id, Suggestion.status, Suggestion.created_at)
        .join(AiSession, Suggestion.session_id == AiSession.id)
        .filter(AiSession.paper_id == paper_id)
        .all()
    )
    suggestions = [
        suggestion_from_row(suggestion_id=sid, status=status, created_at=created_at)
        for sid, status, created_at in suggestion_rows
    ]
    return interactions, suggestions
