/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowRouteImport } from './routes/workflow'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LatexGuideRouteImport } from './routes/latex-guide'
import { Route as IntegrityRouteImport } from './routes/integrity'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as EthicsRouteImport } from './routes/ethics'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as DefenseRouteImport } from './routes/defense'
import { Route as DataUseRouteImport } from './routes/data-use'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as TemplatesRouteRouteImport } from './routes/templates/route'
import { Route as WorkspaceRouteRouteImport } from './routes/_workspace/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplatesIndexRouteImport } from './routes/templates/index'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as WorkspaceProjectsRouteImport } from './routes/_workspace/projects'
import { Route as WorkspaceProfileRouteImport } from './routes/_workspace/profile'
import { Route as WorkspacePlanRouteImport } from './routes/_workspace/plan'
import { Route as WorkspaceGuideRouteImport } from './routes/_workspace/guide'
import { Route as TemplatesTemplateIdIndexRouteImport } from './routes/templates/$templateId/index'
import { Route as TemplatesTemplateIdPdfRouteImport } from './routes/templates/$templateId/pdf'
import { Route as BillingConfirmCheckoutIdRouteImport } from './routes/billing/confirm.$checkoutId'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth/google/callback'

const WorkflowRoute = WorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LatexGuideRoute = LatexGuideRouteImport.update({
  id: '/latex-guide',
  path: '/latex-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrityRoute = IntegrityRouteImport.update({
  id: '/integrity',
  path: '/integrity',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const EthicsRoute = EthicsRouteImport.update({
  id: '/ethics',
  path: '/ethics',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const DefenseRoute = DefenseRouteImport.update({
  id: '/defense',
  path: '/defense',
  getParentRoute: () => rootRouteImport,
} as any)
const DataUseRoute = DataUseRouteImport.update({
  id: '/data-use',
  path: '/data-use',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRouteRoute = TemplatesRouteRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRouteRoute = WorkspaceRouteRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TemplatesRouteRoute,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceProjectsRoute = WorkspaceProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceProfileRoute = WorkspaceProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspacePlanRoute = WorkspacePlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceGuideRoute = WorkspaceGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const TemplatesTemplateIdIndexRoute =
  TemplatesTemplateIdIndexRouteImport.update({
    id: '/$templateId/',
    path: '/$templateId/',
    getParentRoute: () => TemplatesRouteRoute,
  } as any)
const TemplatesTemplateIdPdfRoute = TemplatesTemplateIdPdfRouteImport.update({
  id: '/$templateId/pdf',
  path: '/$templateId/pdf',
  getParentRoute: () => TemplatesRouteRoute,
} as any)
const BillingConfirmCheckoutIdRoute =
  BillingConfirmCheckoutIdRouteImport.update({
    id: '/billing/confirm/$checkoutId',
    path: '/billing/confirm/$checkoutId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/templates': typeof TemplatesRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/data-use': typeof DataUseRoute
  '/defense': typeof DefenseRoute
  '/editor': typeof EditorRoute
  '/ethics': typeof EthicsRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/integrity': typeof IntegrityRoute
  '/latex-guide': typeof LatexGuideRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/workflow': typeof WorkflowRoute
  '/guide': typeof WorkspaceGuideRoute
  '/plan': typeof WorkspacePlanRoute
  '/profile': typeof WorkspaceProfileRoute
  '/projects': typeof WorkspaceProjectsRoute
  '/share/$token': typeof ShareTokenRoute
  '/templates/': typeof TemplatesIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/billing/confirm/$checkoutId': typeof BillingConfirmCheckoutIdRoute
  '/templates/$templateId/pdf': typeof TemplatesTemplateIdPdfRoute
  '/templates/$templateId/': typeof TemplatesTemplateIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/data-use': typeof DataUseRoute
  '/defense': typeof DefenseRoute
  '/editor': typeof EditorRoute
  '/ethics': typeof EthicsRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/integrity': typeof IntegrityRoute
  '/latex-guide': typeof LatexGuideRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/workflow': typeof WorkflowRoute
  '/guide': typeof WorkspaceGuideRoute
  '/plan': typeof WorkspacePlanRoute
  '/profile': typeof WorkspaceProfileRoute
  '/projects': typeof WorkspaceProjectsRoute
  '/share/$token': typeof ShareTokenRoute
  '/templates': typeof TemplatesIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/billing/confirm/$checkoutId': typeof BillingConfirmCheckoutIdRoute
  '/templates/$templateId/pdf': typeof TemplatesTemplateIdPdfRoute
  '/templates/$templateId': typeof TemplatesTemplateIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_workspace': typeof WorkspaceRouteRouteWithChildren
  '/templates': typeof TemplatesRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/data-use': typeof DataUseRoute
  '/defense': typeof DefenseRoute
  '/editor': typeof EditorRoute
  '/ethics': typeof EthicsRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/integrity': typeof IntegrityRoute
  '/latex-guide': typeof LatexGuideRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/workflow': typeof WorkflowRoute
  '/_workspace/guide': typeof WorkspaceGuideRoute
  '/_workspace/plan': typeof WorkspacePlanRoute
  '/_workspace/profile': typeof WorkspaceProfileRoute
  '/_workspace/projects': typeof WorkspaceProjectsRoute
  '/share/$token': typeof ShareTokenRoute
  '/templates/': typeof TemplatesIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/billing/confirm/$checkoutId': typeof BillingConfirmCheckoutIdRoute
  '/templates/$templateId/pdf': typeof TemplatesTemplateIdPdfRoute
  '/templates/$templateId/': typeof TemplatesTemplateIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/templates'
    | '/about'
    | '/admin'
    | '/contact'
    | '/data-use'
    | '/defense'
    | '/editor'
    | '/ethics'
    | '/features'
    | '/forgot-password'
    | '/integrity'
    | '/latex-guide'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/terms'
    | '/workflow'
    | '/guide'
    | '/plan'
    | '/profile'
    | '/projects'
    | '/share/$token'
    | '/templates/'
    | '/auth/google/callback'
    | '/billing/confirm/$checkoutId'
    | '/templates/$templateId/pdf'
    | '/templates/$templateId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/data-use'
    | '/defense'
    | '/editor'
    | '/ethics'
    | '/features'
    | '/forgot-password'
    | '/integrity'
    | '/latex-guide'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/terms'
    | '/workflow'
    | '/guide'
    | '/plan'
    | '/profile'
    | '/projects'
    | '/share/$token'
    | '/templates'
    | '/auth/google/callback'
    | '/billing/confirm/$checkoutId'
    | '/templates/$templateId/pdf'
    | '/templates/$templateId'
  id:
    | '__root__'
    | '/'
    | '/_workspace'
    | '/templates'
    | '/about'
    | '/admin'
    | '/contact'
    | '/data-use'
    | '/defense'
    | '/editor'
    | '/ethics'
    | '/features'
    | '/forgot-password'
    | '/integrity'
    | '/latex-guide'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/terms'
    | '/workflow'
    | '/_workspace/guide'
    | '/_workspace/plan'
    | '/_workspace/profile'
    | '/_workspace/projects'
    | '/share/$token'
    | '/templates/'
    | '/auth/google/callback'
    | '/billing/confirm/$checkoutId'
    | '/templates/$templateId/pdf'
    | '/templates/$templateId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceRouteRoute: typeof WorkspaceRouteRouteWithChildren
  TemplatesRouteRoute: typeof TemplatesRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  DataUseRoute: typeof DataUseRoute
  DefenseRoute: typeof DefenseRoute
  EditorRoute: typeof EditorRoute
  EthicsRoute: typeof EthicsRoute
  FeaturesRoute: typeof FeaturesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  IntegrityRoute: typeof IntegrityRoute
  LatexGuideRoute: typeof LatexGuideRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  WorkflowRoute: typeof WorkflowRoute
  ShareTokenRoute: typeof ShareTokenRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
  BillingConfirmCheckoutIdRoute: typeof BillingConfirmCheckoutIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflow': {
      id: '/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof WorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latex-guide': {
      id: '/latex-guide'
      path: '/latex-guide'
      fullPath: '/latex-guide'
      preLoaderRoute: typeof LatexGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrity': {
      id: '/integrity'
      path: '/integrity'
      fullPath: '/integrity'
      preLoaderRoute: typeof IntegrityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ethics': {
      id: '/ethics'
      path: '/ethics'
      fullPath: '/ethics'
      preLoaderRoute: typeof EthicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/defense': {
      id: '/defense'
      path: '/defense'
      fullPath: '/defense'
      preLoaderRoute: typeof DefenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-use': {
      id: '/data-use'
      path: '/data-use'
      fullPath: '/data-use'
      preLoaderRoute: typeof DataUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof TemplatesRouteRoute
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/projects': {
      id: '/_workspace/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof WorkspaceProjectsRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/profile': {
      id: '/_workspace/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof WorkspaceProfileRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/plan': {
      id: '/_workspace/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof WorkspacePlanRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/guide': {
      id: '/_workspace/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof WorkspaceGuideRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/templates/$templateId/': {
      id: '/templates/$templateId/'
      path: '/$templateId'
      fullPath: '/templates/$templateId/'
      preLoaderRoute: typeof TemplatesTemplateIdIndexRouteImport
      parentRoute: typeof TemplatesRouteRoute
    }
    '/templates/$templateId/pdf': {
      id: '/templates/$templateId/pdf'
      path: '/$templateId/pdf'
      fullPath: '/templates/$templateId/pdf'
      preLoaderRoute: typeof TemplatesTemplateIdPdfRouteImport
      parentRoute: typeof TemplatesRouteRoute
    }
    '/billing/confirm/$checkoutId': {
      id: '/billing/confirm/$checkoutId'
      path: '/billing/confirm/$checkoutId'
      fullPath: '/billing/confirm/$checkoutId'
      preLoaderRoute: typeof BillingConfirmCheckoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface WorkspaceRouteRouteChildren {
  WorkspaceGuideRoute: typeof WorkspaceGuideRoute
  WorkspacePlanRoute: typeof WorkspacePlanRoute
  WorkspaceProfileRoute: typeof WorkspaceProfileRoute
  WorkspaceProjectsRoute: typeof WorkspaceProjectsRoute
}

const WorkspaceRouteRouteChildren: WorkspaceRouteRouteChildren = {
  WorkspaceGuideRoute: WorkspaceGuideRoute,
  WorkspacePlanRoute: WorkspacePlanRoute,
  WorkspaceProfileRoute: WorkspaceProfileRoute,
  WorkspaceProjectsRoute: WorkspaceProjectsRoute,
}

const WorkspaceRouteRouteWithChildren = WorkspaceRouteRoute._addFileChildren(
  WorkspaceRouteRouteChildren,
)

interface TemplatesRouteRouteChildren {
  TemplatesIndexRoute: typeof TemplatesIndexRoute
  TemplatesTemplateIdPdfRoute: typeof TemplatesTemplateIdPdfRoute
  TemplatesTemplateIdIndexRoute: typeof TemplatesTemplateIdIndexRoute
}

const TemplatesRouteRouteChildren: TemplatesRouteRouteChildren = {
  TemplatesIndexRoute: TemplatesIndexRoute,
  TemplatesTemplateIdPdfRoute: TemplatesTemplateIdPdfRoute,
  TemplatesTemplateIdIndexRoute: TemplatesTemplateIdIndexRoute,
}

const TemplatesRouteRouteWithChildren = TemplatesRouteRoute._addFileChildren(
  TemplatesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceRouteRoute: WorkspaceRouteRouteWithChildren,
  TemplatesRouteRoute: TemplatesRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  DataUseRoute: DataUseRoute,
  DefenseRoute: DefenseRoute,
  EditorRoute: EditorRoute,
  EthicsRoute: EthicsRoute,
  FeaturesRoute: FeaturesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  IntegrityRoute: IntegrityRoute,
  LatexGuideRoute: LatexGuideRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  WorkflowRoute: WorkflowRoute,
  ShareTokenRoute: ShareTokenRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
  BillingConfirmCheckoutIdRoute: BillingConfirmCheckoutIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
