from datetime import UTC, datetime, timedelta

from src.db.models import SuggestionStatus, TaskType
from src.services.ai_disclosure import (
    InteractionRecord,
    SuggestionRecord,
    attribute_suggestions,
    build_ai_disclosure_report,
    escape_latex,
    interaction_from_row,
    join_list,
    suggestion_from_row,
)

T0 = datetime(2026, 3, 1, 9, 0, tzinfo=UTC)
GENERATED = datetime(2026, 10, 4, 12, 0, tzinfo=UTC)


def _interaction(
    iid: str,
    task: str,
    minutes: float,
    *,
    provider: str | None = "zai",
    model: str | None = "glm-4.7-flash",
    revision_id: str | None = None,
    legacy: bool = False,
) -> InteractionRecord:
    return InteractionRecord(
        id=iid,
        task=task,
        created_at=T0 + timedelta(minutes=minutes),
        provider=provider,
        model=model,
        revision_id=revision_id,
        legacy=legacy,
    )


def _suggestion(sid: str, status: str, minutes: float) -> SuggestionRecord:
    return SuggestionRecord(id=sid, status=status, created_at=T0 + timedelta(minutes=minutes))


def _report(interactions, suggestions):
    return build_ai_disclosure_report(
        paper_id="paper-1",
        paper_title="My Paper",
        interactions=interactions,
        suggestions=suggestions,
        generated_at=GENERATED,
    )


def _task_row(report, task):
    return next(row for row in report.by_task if row.task == task)


# ─── No AI usage ─────────────────────────────────────────────────────────────


def test_no_ai_usage_reports_honestly():
    report = _report([], [])

    assert report.has_ai_usage is False
    assert report.totals.interactions == 0
    assert report.totals.proposed == 0
    assert report.by_task == []
    assert report.models == []
    assert report.period.first_interaction_at is None
    assert report.period.last_interaction_at is None
    assert report.statement.en.startswith("No use of Arionear's AI writing assistant was recorded")
    assert "used Arionear" not in report.statement.en
    assert report.statement.vi.startswith("Không ghi nhận việc sử dụng trợ lý viết AI của Arionear")
    assert "% AI disclosure generated by Arionear on 2026-10-04" in report.latex.en
    assert "\\section*{Declaration of generative AI" in report.latex.en
    assert report.data_sources == ["ai_sessions", "suggestions"]


def test_placeholder_sessions_are_not_interactions():
    placeholder = interaction_from_row(
        session_id="s0",
        task_type=TaskType.CHAT,
        created_at=T0,
        metadata={},
        tokens_used=0,
        input_chars=0,
        output_chars=0,
    )
    assert placeholder is None


# ─── Mixed accept / reject ───────────────────────────────────────────────────


def test_mixed_accept_reject_counts_and_statement():
    interactions = [
        _interaction("i1", "style", 1, revision_id="s1"),
        _interaction("i2", "style", 2, revision_id="s2"),
        _interaction("i3", "edit", 3, revision_id="s3"),
        _interaction("i4", "edit", 4, revision_id="s4"),
        _interaction("i5", "edit", 5, revision_id="s5"),
    ]
    suggestions = [
        _suggestion("s1", "accepted", 0.5),
        _suggestion("s2", "rejected", 1.5),
        _suggestion("s3", "modified", 2.5),
        _suggestion("s4", "accepted", 3.5),
        _suggestion("s5", "pending", 4.5),
    ]
    report = _report(interactions, suggestions)

    assert report.has_ai_usage is True
    totals = report.totals
    assert (totals.interactions, totals.proposed) == (5, 5)
    assert (totals.accepted, totals.modified, totals.rejected, totals.pending) == (2, 1, 1, 1)
    assert report.attribution.model_dump() == {"linked": 5, "inferred": 0, "unattributed": 0}

    style = _task_row(report, "style")
    assert (style.interactions, style.proposed, style.accepted, style.rejected) == (2, 2, 1, 1)
    edit = _task_row(report, "edit")
    assert (edit.interactions, edit.proposed, edit.accepted, edit.modified, edit.pending) == (3, 3, 1, 1, 1)

    en = report.statement.en
    assert "Arionear proposed 5 text revisions" in en
    assert "3 accepted (1 after modification by the author(s)), 1 rejected, and 1 left undecided." in en
    assert "None of the AI-proposed revisions" not in en
    assert "take(s) full responsibility for the content of the publication" in en

    vi = report.statement.vi
    assert "Arionear đã đề xuất 5 chỉnh sửa văn bản" in vi
    assert "3 được chấp nhận (trong đó 1 được tác giả sửa lại trước khi chấp nhận), 1 bị từ chối" in vi
    assert "1 chưa được quyết định" in vi
    assert "chịu hoàn toàn trách nhiệm" in vi

    assert report.period.first_interaction_at == T0 + timedelta(minutes=0.5)
    assert report.period.last_interaction_at == T0 + timedelta(minutes=5)


def test_nothing_accepted_is_stated_explicitly():
    interactions = [_interaction("i1", "style", 1, revision_id="s1"), _interaction("i2", "style", 2)]
    suggestions = [_suggestion("s1", "rejected", 0.5)]
    report = _report(interactions, suggestions)

    assert report.totals.accepted == 0
    assert "Arionear proposed 1 text revision," in report.statement.en
    assert "0 accepted and 1 rejected." in report.statement.en
    assert "None of the AI-proposed revisions were accepted into the manuscript." in report.statement.en
    assert "Không có đề xuất chỉnh sửa nào của AI được đưa vào bản thảo." in report.statement.vi


def test_usage_without_revisions_says_no_revisions_recorded():
    report = _report([_interaction("i1", "citation", 1)], [])

    assert report.has_ai_usage is True
    assert report.totals.proposed == 0
    assert "to check and verify bibliographic references." in report.statement.en
    assert "No AI-proposed text revisions were recorded" in report.statement.en
    assert "Arionear proposed" not in report.statement.en


# ─── Task types ──────────────────────────────────────────────────────────────


def test_multiple_task_types_only_mentions_tasks_that_occurred():
    interactions = [
        _interaction("i1", "logic", 1),
        _interaction("i2", "citation", 2),
        _interaction("i3", "style", 3, revision_id="s1"),
        _interaction("i4", "citation", 4),
    ]
    suggestions = [_suggestion("s1", "accepted", 2.9)]
    report = _report(interactions, suggestions)

    # Canonical order, not chronological order.
    assert [row.task for row in report.by_task] == ["style", "citation", "logic"]
    assert _task_row(report, "citation").interactions == 2

    en = report.statement.en
    assert (
        "to improve the language, grammar and style of selected passages, check and verify bibliographic "
        "references, and audit the logical consistency of the argumentation." in en
    )
    for absent in ("template", "structure of the manuscript", "answer questions", "draft and revise"):
        assert absent not in en

    vi = report.statement.vi
    assert "kiểm tra và xác minh tài liệu tham khảo và rà soát tính nhất quán logic của lập luận." in vi
    assert "khung mẫu LaTeX" not in vi


def test_models_are_deduplicated_and_described():
    interactions = [
        _interaction("i1", "chat", 1, provider="zai", model="glm-4.7-flash"),
        _interaction("i2", "chat", 2, provider="zai", model="glm-4.7-flash"),
        _interaction("i3", "chat", 3, provider="google", model=None),
        _interaction("i4", "chat", 4, provider=None, model=None),
    ]
    report = _report(interactions, [])

    assert [(m.provider, m.model, m.interactions) for m in report.models] == [
        ("zai", "glm-4.7-flash", 2),
        ("google", None, 1),
    ]
    assert report.models[1].provider_label == "Google Gemini"
    assert "(models: glm-4.7-flash via Z.AI GLM and Google Gemini)" in report.statement.en
    assert "(mô hình: glm-4.7-flash qua Z.AI GLM và Google Gemini)" in report.statement.vi


def test_single_model_uses_singular_label():
    report = _report([_interaction("i1", "chat", 1)], [])
    assert "(model: glm-4.7-flash via Z.AI GLM)" in report.statement.en


# ─── Attribution of suggestions to tasks ─────────────────────────────────────


def test_legacy_rows_are_inferred_by_time_window_and_chat_becomes_edit():
    interactions = [
        _interaction("old-style", "style", 1, legacy=True),
        _interaction("old-chat", "chat", 6, legacy=True),
        _interaction("old-chat-2", "chat", 7, legacy=True),
        _interaction("old-logic", "logic", 60.5, legacy=True),
    ]
    suggestions = [
        _suggestion("s1", "accepted", 0.9),  # → old-style
        _suggestion("s2", "rejected", 5.9),  # → old-chat, relabelled edit
        _suggestion("s3", "accepted", 60),  # logic never produces suggestions → unattributed
    ]
    attribution = attribute_suggestions(interactions, suggestions)

    assert attribution.task_by_suggestion == {"s1": "style", "s2": "edit", "s3": None}
    assert attribution.task_by_interaction["old-chat"] == "edit"
    assert attribution.task_by_interaction["old-chat-2"] == "chat"
    assert (attribution.linked, attribution.inferred, attribution.unattributed) == (0, 2, 1)

    report = _report(interactions, suggestions)
    assert [row.task for row in report.by_task] == ["style", "edit", "logic", "chat"]
    assert report.unattributed.proposed == 1
    assert report.unattributed.accepted == 1


def test_inference_ignores_interactions_outside_window_and_new_rows():
    interactions = [
        _interaction("late", "style", 30, legacy=True),  # beyond the 10-minute window
        _interaction("new-style", "style", 1),  # new rows only match by explicit revision_id
    ]
    attribution = attribute_suggestions(interactions, [_suggestion("s1", "accepted", 0)])
    assert attribution.task_by_suggestion == {"s1": None}
    assert attribution.unattributed == 1


def test_suggestions_without_any_known_task_still_count():
    report = _report([], [_suggestion("s1", "accepted", 0)])

    assert report.has_ai_usage is True
    assert report.by_task == []
    assert report.totals.proposed == 1
    assert "to propose revisions to the text." in report.statement.en
    assert "để đề xuất chỉnh sửa văn bản." in report.statement.vi


# ─── Row conversion ──────────────────────────────────────────────────────────


def test_interaction_from_row_reads_metadata_and_normalizes():
    naive = datetime(2026, 3, 1, 9, 0)
    record = interaction_from_row(
        session_id="abc",
        task_type=TaskType.CHAT,
        created_at=naive,
        metadata={"task": "edit", "llm_provider": "ZAI", "llm_model": " glm-4.7 ", "revision_id": "REV-1"},
        tokens_used=0,
        input_chars=12,
        output_chars=0,
    )
    assert record is not None
    assert record.task == "edit"
    assert record.legacy is False
    assert record.provider == "zai"
    assert record.model == "glm-4.7"
    assert record.revision_id == "rev-1"
    assert record.created_at.tzinfo is not None

    legacy = interaction_from_row(
        session_id="def",
        task_type=TaskType.LOGIC,
        created_at=naive,
        metadata=None,
        tokens_used=50,
        input_chars=0,
        output_chars=0,
    )
    assert legacy is not None
    assert (legacy.task, legacy.legacy) == ("logic", True)


def test_suggestion_from_row_normalizes_status():
    assert suggestion_from_row(suggestion_id="X", status=SuggestionStatus.MODIFIED, created_at=T0).status == "modified"
    assert suggestion_from_row(suggestion_id="X", status=SuggestionStatus.PENDING, created_at=T0).status == "pending"
    assert suggestion_from_row(suggestion_id="X", status="weird", created_at=T0).status == "pending"
    assert suggestion_from_row(suggestion_id="ABC", status="accepted", created_at=T0).id == "abc"


# ─── Text helpers / LaTeX ────────────────────────────────────────────────────


def test_escape_latex_special_characters():
    assert escape_latex("50% & $x_1$ #1 {a} \\ ~ ^ <b> |") == (
        r"50\% \& \$x\_1\$ \#1 \{a\} \textbackslash{} \textasciitilde{} \textasciicircum{} "
        r"\textless{}b\textgreater{} \textbar{}"
    )
    assert escape_latex("author's work") == "author's work"


def test_latex_snippet_escapes_model_names():
    interactions = [_interaction("i1", "style", 1, provider="openrouter", model="my_model~v2 & co")]
    report = _report(interactions, [])

    latex = report.latex.en
    lines = latex.splitlines()
    assert lines[0].startswith("% AI disclosure generated by Arionear on 2026-10-04")
    assert lines[1] == "\\section*{Declaration of generative AI and AI-assisted technologies in the writing process}"
    assert r"my\_model\textasciitilde{}v2 \& co via OpenRouter" in latex
    assert "my_model" not in latex
    assert "my_model~v2 & co" in report.statement.en  # plain statement stays unescaped
    assert "\\section*{Tuyên bố về việc sử dụng AI tạo sinh" in report.latex.vi


def test_join_list():
    assert join_list([], "en") == ""
    assert join_list(["a"], "en") == "a"
    assert join_list(["a", "b"], "en") == "a and b"
    assert join_list(["a", "b", "c"], "en") == "a, b, and c"
    assert join_list(["a", "b", "c"], "vi") == "a, b và c"
