/** Terms that must never become PDF citation search targets. */

export const PDF_CITATION_STOPWORDS = new Set([
  // Vietnamese function words / pronouns
  "trong",
  "cho",
  "của",
  "cua",
  "và",
  "va",
  "là",
  "la",
  "có",
  "co",
  "được",
  "duoc",
  "này",
  "nay",
  "đó",
  "do",
  "các",
  "cac",
  "một",
  "mot",
  "với",
  "voi",
  "từ",
  "tu",
  "khi",
  "như",
  "nhu",
  "về",
  "ve",
  "tại",
  "tai",
  "bạn",
  "ban",
  "tôi",
  "toi",
  "để",
  "de",
  "hoặc",
  "hoac",
  "hay",
  "cũng",
  "cung",
  "đã",
  "da",
  "sẽ",
  "se",
  "bối",
  "boi",
  "cảnh",
  "canh",
  "những",
  "nhung",
  "gì",
  "gi",
  "không",
  "khong",
  "còn",
  "con",
  "cũng",
  // English stopwords
  "the",
  "and",
  "for",
  "with",
  "from",
  "this",
  "that",
  "using",
  "use",
  "used",
  "paper",
  "section",
  "figure",
  "table",
  "abstract",
  "introduction",
  "conclusion",
  "chapter",
  "in",
  "on",
  "at",
  "to",
  "of",
  "by",
  "an",
  "or",
  "as",
  "is",
  "are",
  "was",
  "be",
  "been",
  "it",
  "its",
  "we",
  "you",
  "your",
]);

export function isValidPdfCitationSearch(search: string): boolean {
  const normalized = search.trim().toLowerCase();
  if (!normalized) return false;
  if (PDF_CITATION_STOPWORDS.has(normalized)) return false;
  if (normalized.length < 4) return false;
  // Plain short lowercase tokens (e.g. author surnames mis-linked) — require tech shape or length.
  const hasUpper = /[A-Z]/.test(search);
  const hasHyphen = search.includes("-");
  const isMultiWord = normalized.split(/\s+/).length >= 2;
  if (!hasUpper && !hasHyphen && !isMultiWord && normalized.length < 6) return false;
  return true;
}
